### ISSUE TITLE
[check] Some tests fail

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/DEPRECATED-lesson-template#42]
```
$ git rev-parse HEAD
5c4e7bb6363906d9b1d03673fa853fe22c3403d4
$ pwd
lesson-template/tools
$ python test_markdown.py
(...)
======================================================================
FAIL: test_sample_file_passes_validation (__main__.TestDiscussionPage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_markdown.py", line 313, in test_sample_file_passes_validation
    self.assertTrue(res)
AssertionError: False is not true

======================================================================
FAIL: test_file_links_validate (__main__.TestIndexPage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_markdown.py", line 183, in test_file_links_validate
    self.assertTrue(res)
AssertionError: False is not true

======================================================================
FAIL: test_html_link_to_extant_md_file_passes (__main__.TestIndexPage)
Verify that an HTML link with corresponding MD file will pass
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_markdown.py", line 188, in test_html_link_to_extant_md_file_passes
    self.assertTrue(validator._validate_links())
AssertionError: False is not true

======================================================================
FAIL: test_html_linkwithanchor_to_extant_md_passes (__main__.TestIndexPage)
Verify that link is identified correctly even if to page anchor
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_markdown.py", line 197, in test_html_linkwithanchor_to_extant_md_passes
    self.assertTrue(validator._validate_links())
AssertionError: False is not true

======================================================================
FAIL: test_sample_file_passes_validation (__main__.TestIndexPage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_markdown.py", line 46, in test_sample_file_passes_validation
    self.assertTrue(res)
AssertionError: False is not true

======================================================================
FAIL: test_sample_file_passes_validation (__main__.TestInstructorPage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_markdown.py", line 288, in test_sample_file_passes_validation
    self.assertTrue(res)
AssertionError: False is not true

======================================================================
FAIL: test_sample_file_passes_validation (__main__.TestReferencePage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_markdown.py", line 278, in test_sample_file_passes_validation
    self.assertTrue(res)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 30 tests in 0.197s

FAILED (failures=7)
```

@abought Any comment?

**Comment by abought** [comment]
This is a solid find, @r-gaia-cs : ensuring the validator is actually up to spec is a major priority for me. Thanks! 

I've made some small changes (a bugfix and some test cleanup) that bring the number of failed tests down to two. 

The failure of Reference and Instructor was due to a bug when I switched these validators over to allow headings besides the ones included in the spec. Fixed; my fault for not running the tests before committing.

The failures in index.md are due to the same issue: things that require template changes. Running the tool directly on index.md returns the following errors:

```
DEBUG:root:Beginning validation of pages/index.md using template index
ERROR:root:In pages/index.md: The linked page motivation.html exists, but the link text 'Motivation' does not match the (sub)title of that page, ''.
ERROR:root:In pages/index.md: The linked page reference.html exists, but the link text 'Reference Guide' does not match the (sub)title of that page, 'Reference'.
ERROR:root:In pages/index.md: The linked page discussion.html exists, but the link text 'Next Steps' does not match the (sub)title of that page, 'Discussion'.
DEBUG:root:File pages/index.md failed validation: see error log for details
```

### Recommended actions:
1. Motivation.md should have a "subtitle" section in the header.
2. The link text in three index.md links should be updated to reflect the subtitle specified in the documents (see above error messages)

**Comment by rgaiacs** [comment]
> ```
> DEBUG:root:Beginning validation of pages/index.md using template index
> ERROR:root:In pages/index.md: The linked page motivation.html exists, but the link text 'Motivation' does not match the (sub)title of that page, ''.
> ERROR:root:In pages/index.md: The linked page reference.html exists, but the link text 'Reference Guide' does not match the (sub)title of that page, 'Reference'.
> ERROR:root:In pages/index.md: The linked page discussion.html exists, but the link text 'Next Steps' does not match the (sub)title of that page, 'Discussion'.
> DEBUG:root:File pages/index.md failed validation: see error log for details
> ```

I did notice this erros. I didn't mention it because I was thinking what we
should do and maybe they are the only cases that we should avoid check the title
of the files. Why? `motivation.html` is the slide deck to start the session and
the title of the slide deck propably won't be "Motivation".

**Comment by rgaiacs** [comment]
Close since this was covered in #35.
